const maincontainer = document.createElement("div");
const bluebox = document.createElement("div");
const whitebox = document.createElement("div");
const texts = document.createElement("div");
const buttonside = document.createElement("div");
const button1 = document.createElement("button");
const button2 = document.createElement("button");
const boxes = document.createElement("div");
const body = document.body;
const h5 = document.createElement("h5");
const h1 = document.createElement("h1");
const h3 = document.createElement("h3");
const box1 = document.createElement("div");
const box2 = document.createElement("div");
const box3 = document.createElement("div");
const h6 = document.createElement("h6");
const h2 = document.createElement("h2");
const h4 = document.createElement("h4");
const image1 = new Image(70, 72);
const image2 = new Image(70, 72);
const image3 = new Image(70, 72);
const image4 = new Image(50, 2);
const image5 = new Image(50, 2);
const image6 = new Image(50, 2);
const IIh5 = document.createElement("h5");
const IIIh5 = document.createElement("h5");
const IVh5 = document.createElement("h5");
const par = document.createElement("p");
const parr = document.createElement("p");
const par2 = document.createElement("p");
const inpdiv = document.createElement("div");
const input = document.createElement("input");
const button3 = document.createElement("button");


image1.src = 'assets/emoji.png';
image2.src = 'assets/check.png';
image3.src = 'assets/card.png';
image4.src = 'assets/line.png';
image5.src = 'assets/line.png';
image6.src = 'assets/whiteline.png';


h5.innerHTML = "Welcome";
h1.innerHTML = "Selling on the internet like a pro";
h3.innerHTML = "We know how large objects will act, but things on a small scale just do not act that way.";
button1.innerHTML = "Get Quote Now";
button2.innerHTML = "Learn More";
button3.innerHTML = "Subscribe";
h6.innerHTML = "Practice Advice";
h2.innerHTML = "Featured Products";
h4.innerHTML = "Problems trying to resolve the conflict between the two major realms of Classical physics: Newtonian mechanics";
IIh5.innerHTML = "training Courses";
IIIh5.innerHTML = "2,769 online courses";
IVh5.innerHTML = "training Courses";
par.innerHTML = "The gradual accumulation of information about atomic and small-scale behaviour...";
parr.innerHTML = "The gradual accumulation of information about atomic and small-scale behaviour...";
par2.innerHTML = "The gradual accumulation of information about atomic and small-scale behaviour..."
input.placeholder = "Your Email";


bluebox.style.background = "#252B42";
bluebox.style.padding = '140px 195px 80px 195px';
bluebox.style.display = "flex";
bluebox.style.alignItems = "center"
bluebox.style.flexDirection = "column";
bluebox.style.gap = "30px";
body.style.margin = "0";
body.style.padding = "0";
texts.style.display = "flex";
texts.style.flexDirection = "column";
texts.style.alignItems = "center";
h5.style.fontSize = "16px";
h5.style.fontWeight = "700";
h5.style.color = "#23A6F0";
h1.style.fontSize = "58px";
h1.style.fontWeight = "700";
h1.style.width = "550px";
h1.style.lineHeight = "80px";
h1.style.textAlign = "center";
h1.style.color = "white";
h3.style.fontSize = "20px";
h3.style.fontWeight = "400";
h3.style.width = "515px";
h3.style.lineHeight = "30px";
h3.style.textAlign = "center";
h3.style.color = "white";
buttonside.style.display = "flex";
buttonside.style.alignItems = "center";
buttonside.style.gap = "10px";
button1.style.width = "162px";
button1.style.height = "52px";
button1.style.background = "#23A6F0";
button1.style.border = "none";
button1.style.color = "white";
button1.style.borderRadius = "5px";
button1.style.cursor = "pointer";
button2.style.width = "162px";
button2.style.height = "52px";
button2.style.borderRadius = "5px";
button2.style.border = "1px solid var(--primary-color, #23A6F0)";
button2.style.background = "transparent";
button2.style.color = "#23A6F0";
button2.style.cursor = "pointer";
boxes.style.display = "flex";
boxes.style.alignItems = "center";
boxes.style.gap = "30px";
boxes.style.marginTop = "60px";
box1.style.background = "white";
box1.style.display = "flex";
box1.style.flexDirection = "column";
box1.style.padding = "35px 40px";
box2.style.background = "white";
box2.style.padding = "35px 40px";
box2.style.display = "flex";
box2.style.flexDirection = "column";
box3.style.padding = "35px 40px";
box3.style.background = "#23A6F0";
box3.style.display = "flex";
box3.style.flexDirection = "column";
whitebox.style.display = "flex";
whitebox.style.flexDirection = "column";
whitebox.style.alignItems = "center";
whitebox.style.gap = "15px";
whitebox.style.padding = "160px 200px"
h6.style.margin = "0";
h6.style.fontSize = "14px";
h6.style.fontWeight = "700";
h6.style.color = "#23A6F0";
h2.style.margin = "0";
h2.style.fontSize = "40px";
h2.style.fontWeight = "700";
h2.style.color = "#252B42";
h4.style.margin = "0";
h4.style.fontSize = "14px"
h4.style.fontWeight = "400";
h4.style.color = "#737373";
h4.style.width = "410px";
h4.style.letterSpacing = "0.2px"
h4.style.lineHeight = "20px";
h4.style.textAlign = "center";
par.style.width = "230px";
par.style.fontSize = "14px";
par.style.color = "#737373";
par.style.fontWeight = "400";
parr.style.width = "230px";
parr.style.fontSize = "14px";
parr.style.color = "#737373";
parr.style.fontWeight = "400";
IVh5.style.color = "white";
par2.style.color = "white";
par2.style.width = "230px";
par2.style.fontSize = "14px";
par2.style.fontWeight = "400";
inpdiv.style.marginTop = "60px";
input.style.width = "500px";
input.style.height = "55px";
input.style.padding = "0 20px";
input.style.background = "#F9F9F9";
input.style.border = "1px solid #E6E6E6";
input.style.fontSize = "14px";
input.style.fontWeight = "400";
button3.style.height = "57px";
button3.style.width = "110px";
button3.style.borderRadius = "0px 5px 5px 0px";
button3.style.border = "none";
button3.style.background = "#23A6F0";
button3.style.color = "white";
button3.style.fontSize = "14px";
button3.style.fontWeight = "400";
button3.style.cursor = "pointer";


document.body.appendChild(maincontainer);
maincontainer.appendChild(bluebox);
maincontainer.appendChild(whitebox);
bluebox.appendChild(texts);
texts.appendChild(h5);
texts.appendChild(h1);
texts.appendChild(h3);
bluebox.appendChild(buttonside);
buttonside.appendChild(button1);
buttonside.appendChild(button2);
bluebox.appendChild(boxes);
boxes.appendChild(box1);
boxes.appendChild(box2);
boxes.appendChild(box3);
whitebox.appendChild(h6);
whitebox.appendChild(h2);
whitebox.appendChild(h4);
whitebox.appendChild(inpdiv);
box1.appendChild(image1);
box1.appendChild(IIh5);
box1.appendChild(image4);
box1.appendChild(par);
box2.appendChild(image2);
box2.appendChild(IIIh5);
box2.appendChild(image5);
box2.appendChild(parr);
box3.appendChild(image3);
box3.appendChild(IVh5);
box3.appendChild(image6);
box3.appendChild(par2);
inpdiv.appendChild(input);
inpdiv.appendChild(button3);




